//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Required")]
        public string fname { get; set; }

        [Required(ErrorMessage = "Required")]
        public string lname { get; set; }

        [MinLength(10,ErrorMessage="Mobile No. Should be 10 digits")]
        public string contact { get; set; }

        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        public string email { get; set; }

        [Required(ErrorMessage = "Required")]
        public string address { get; set; }
    }
}
